version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: wish-api-dev
    command: npm run dev
    volumes:
      - ./api/:/usr/src/app/
      - /usr/src/app/node_modules
    command: npm run dev
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - MONGO_URL=${MONGO_URL}
      - API_PORT=${API_PORT}
    depends_on:
      - mongo
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: wish-client-dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - api
  mongo:
    image: mongo
    volumes:
      - ./data/dev:/data/db
    ports:
      - "27017:27017"